project_urls:
    Source Code: https://sylvainprigent.github.io/napari-stracking
    Project Site: https://sylvainprigent.github.io/napari-stracking/
    Documentation: https://sylvainprigent.github.io/napari-stracking/guide.html
    Bug Tracker: https://github.com/sylvainprigent/napari-stracking/issues
    User Support: https://github.com/sylvainprigent/napari-stracking/issues
    Twitter: https://twitter.com/SylvainMPrigent

# Add labels the plugin from the EDAM Bioimaging ontology
labels:
  ontology: EDAM-BIOIMAGING:alpha06
  terms:
  - Particle tracking
  - 2D image
  - 3D image
  - Image time series
