name: tests

on:
  push:
    branches:
      - master
      - main
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  release_sphinx:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:

      # check out sources that will be used for autodocs, plus readme
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install rsync
        run: |
          apt-get update && apt-get install -y rsync

      - name: Napari linux
        run: |
          apt-get install -y libdbus-1-3 libxkbcommon-x11-0 libxcb-icccm4 \
                    libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 \
                    libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0 ffmpeg libsm6 libxext6 \
                    libgl1-mesa-glx
      # didn't need to change anything here, but had to add sphinx.ext.githubpages
      # to my conf.py extensions list. that fixes the broken uploads
      - name: Building documentation
        run: |
          pip install cython numpy scikit-image scipy stracking napari magicgui pytest-qt qtpy pyqt5 napari-plugin-engine
          pip install sphinx sphinx_rtd_theme
          cd docs
          make html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/_build/html # The folder the action should deploy.
